
// Objective-C API for talking to the following Go packages
//
//	github.com/algorand/go-algorand-sdk/auction
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Auction_FRAMEWORK_H__
#define __Auction_FRAMEWORK_H__

#include "Auction.objc.h"
#include "Universe.objc.h"

#endif
