// Objective-C API for talking to github.com/algorand/go-algorand-sdk/auction Go package.
//   gobind -lang=objc github.com/algorand/go-algorand-sdk/auction
//
// File is generated by gobind. Do not edit.

#ifndef __Auction_H__
#define __Auction_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


/**
 * MakeBid constructs a bid using the passed parameters. `bidderAddress` and
`auctionAddress` should be checksummed, human-readable addresses
 */
FOUNDATION_EXPORT NSData* _Nullable AuctionMakeBid(NSString* _Nullable bidderAddress, int64_t bidAmount, int64_t maxPrice, int64_t bidID, NSString* _Nullable auctionAddress, int64_t auctionID, NSError* _Nullable* _Nullable error);

#endif
