// Objective-C API for talking to github.com/algorand/go-algorand-sdk/mnemonic Go package.
//   gobind -lang=objc github.com/algorand/go-algorand-sdk/mnemonic
//
// File is generated by gobind. Do not edit.

#ifndef __Mnemonic_H__
#define __Mnemonic_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


/**
 * FromKey converts a 32-byte key into a 25 word mnemonic. The generated
mnemonic includes a checksum. Each word in the mnemonic represents 11 bits
of data, and the last 11 bits are reserved for the checksum.
 */
FOUNDATION_EXPORT NSString* _Nonnull MnemonicFromKey(NSData* _Nullable key, NSError* _Nullable* error);

// skipped function FromMasterDerivationKey with unsupported parameter or return types


// skipped function FromPrivateKey with unsupported parameter or return types


/**
 * ToKey converts a mnemonic generated using this library into the source
key used to create it. It returns an error if the passed mnemonic has an
incorrect checksum, if the number of words is unexpected, or if one
of the passed words is not found in the words list.
 */
FOUNDATION_EXPORT NSData* _Nullable MnemonicToKey(NSString* _Nullable mnemonic, NSError* _Nullable* error);

// skipped function ToMasterDerivationKey with unsupported parameter or return types


// skipped function ToPrivateKey with unsupported parameter or return types


#endif
