// Objective-C API for talking to github.com/algorand/go-algorand-sdk/encoding/msgpack Go package.
//   gobind -lang=objc github.com/algorand/go-algorand-sdk/encoding/msgpack
//
// File is generated by gobind. Do not edit.

#ifndef __Msgpack_H__
#define __Msgpack_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@interface Msgpack : NSObject
// skipped variable CodecHandle with unsupported type: *github.com/algorand/go-algorand-sdk/vendor/github.com/algorand/go-codec/codec.MsgpackHandle

@end

// skipped function Decode with unsupported parameter or return types


// skipped function Encode with unsupported parameter or return types


// skipped function NewDecoder with unsupported parameter or return types


#endif
