// Objective-C API for talking to github.com/algorand/go-algorand-sdk/transaction Go package.
//   gobind -lang=objc github.com/algorand/go-algorand-sdk/transaction
//
// File is generated by gobind. Do not edit.

#ifndef __Transaction_H__
#define __Transaction_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


/**
 * MakePaymentTxn constructs a payment transaction using the passed parameters.
`from` and `to` addresses should be checksummed, human-readable addresses
 */
FOUNDATION_EXPORT NSData* _Nullable TransactionMakePaymentTxn(NSString* _Nullable from, NSString* _Nullable to, int64_t fee, int64_t amount, int64_t firstRound, int64_t lastRound, NSData* _Nullable note, NSString* _Nullable closeRemainderTo, NSString* _Nullable genesisID, NSError* _Nullable* error);

#endif
